### ISSUE TITLE
Does not function yet

### ISSUE THREAD

**Issue by WillemOuwerkerk** [ataradov/usb-sniffer-lite#10]
Hi Ataradov,

I installed the UF2 and made me a primitive cable.
Can get the menu in a terminal screen, but i can't get it to capture any data.
Both USB connectors are connected to the same bus.

And i do not understand the function of the start key, can you explain this to me?

Kind regards,
Willem Ouwerkerk

**Comment by ataradov** [comment]
What do you mean by the "same bus"? Can you describe your connections in more detail? What is your device under test?

The start key actually starts the capture.

**Comment by WillemOuwerkerk** [comment]
They are connected to the same USB hub
What is the difference between the START key and the trigger key?
My first device is an USB to RS232 dongle

**Comment by ataradov** [comment]
What exact device you are trying to capture? What IC is it based on? Are you sure it is FS/LS device?

Trigger is not a key, it is a signal. If enabled, then after you start the capture, the sniffer will wait for the trigger signal. It is useful if you are debugging your own firmware and can toggle a GPIO at the point of interest. If you are capturing existing devices, then trigger is rarely useful. Disable it.

**Comment by WillemOuwerkerk** [comment]
Ok now i understand it's function, nice.
The dongle is a PL2302just to try it out
I want to use it to write a custom RP2040 usb driver

**Comment by ataradov** [comment]
PL2302 is a Full-Speed device, so you should be able to capture it. If you don't see any frames when you start the capture, then you will have to provide more details of your setup.

What custom USB driver? I'm confused.

**Comment by WillemOuwerkerk** [comment]
Oh i just want to understand the built-in USB of the RP2040

![usb dongles](https://github.com/ataradov/usb-sniffer-lite/assets/11397265/c68deab9-f184-47bc-b4c4-09752365e76d)

![afbeelding](https://github.com/ataradov/usb-sniffer-lite/assets/11397265/8f06f81f-80d4-4abe-9b36-13b419a5dcf5)

**Comment by ataradov** [comment]
This photo is not useful at all. There is nothing I can tell from it. 

If you just want to understand USB part, then this project may be more useful https://github.com/ataradov/free-dap/tree/master/platform/rp2040 It is a CMSIS-DAP programmer + VCP without complexities of the sniffer part.

**Comment by WillemOuwerkerk** [comment]
What do you need to know from me tot help me?
Is the start key toggle or need i keep it pressed?

made the simple connector as you adviced to GPIO10 & 11
A switch to GPIO12 and the status led blinks

I plugged all devices including the sniffer in the same usb-hub.

**Comment by ataradov** [comment]
I need a diagram of all your connections.

Actually, it makes no sense. The USB bus from the IC to the hub here is inside the plug. And this is the bus you want to observe.

This style of simple splice only works for devices with mini/micro USB connector. This way you can take a standard USB-A to micor-USB cable and tap in the middle.

The sniffer can't capture anything thorough the hub, it need to observe the bus between the hub and the device.

Plugging in the target interface (GPIO10 and 11) into the hub will do nothing, since hub does not carry any data on those pins if there is no device connected to that port.

**Comment by WillemOuwerkerk** [comment]
Hi Alex,

Now i think that i start to understand how it must be used. Is it like this?

![afbeelding](https://github.com/ataradov/usb-sniffer-lite/assets/11397265/d630ed8b-9020-4b4c-ad1f-8bbd350d5639)

**Comment by ataradov** [comment]
Yes, exactly. The sniffer passively observes the communication.

**Comment by WillemOuwerkerk** [comment]
Thanks, i am going to make the correct cable
Also thanks for the pointer to your example code

**Comment by WillemOuwerkerk** [comment]
Thanks Alex, it's working now

**Comment by ataradov** [comment]
Closing the issue then.
