### ISSUE TITLE
BIN2UF2 PROBLEM

### ISSUE THREAD

**Issue by 1250364116** [ataradov/usb-sniffer-lite#12]
Hi. i tried to compile your code in Ubuntu, I have ARM GCC and Make in my Linux PATH. but when i try to run Makefile it gives an error
that bin2uf2 does not exist. I tried to find bin2uf2 for ubuntu but didn't find something useful. Where did you find bin2uf2?

**Comment by ataradov** [comment]
It is linked in the main readme https://github.com/ataradov/tools/tree/master/bin2uf2 I've also edited it just now to make it even more apparent.

**Comment by 1250364116** [comment]
thanks a lot

**Comment by stappersg** [comment]
> thanks a lot

Acknowledge on the _"thanks a lot"_. Now this issue waits for someone to close it. (So this issue would**n't** drain further human energy.)
