### ISSUE TITLE
other rp2040 libraries

### ISSUE THREAD

**Issue by 1250364116** [ataradov/usb-sniffer-lite#15]
hello. i think your libraries for rp2040 is far more better for developing new programs by rp2040 than its SDK libraries distributed by its company. i want to know, have you developed libraries for other rp2040 peripherals like SPI or UART? if yes, can I have those?

**Comment by ataradov** [comment]
Simple UART example is available here https://github.com/ataradov/mcu-starter-projects/blob/master/rp2040/main.c
A more complete example is here https://github.com/ataradov/free-dap/blob/master/platform/rp2040/uart.c

I don't have examples for SPI.
