### ISSUE TITLE
buffer size for capture the data

### ISSUE THREAD

**Issue by 1250364116** [ataradov/usb-sniffer-lite#17]
Hi, I’d like to understand the reason behind choosing a buffer size of 232 kilobytes. If I were to halve this size to create some extra free space for RAM, would it have any impact or change the behavior of the system?

**Comment by ataradov** [comment]
This is just the biggest buffer to use the remaining RAM. You can reduce this size to free up more RAM for your code.
Keep in mind that the linker script here does not reserve the stack stack size. The stack is just the leftover RAM at the end. So make sure that you still have a couple KB left for the stack.
