### ISSUE TITLE
HOW is boot crc converted from 0xcccccccc to something the boot ROM accepts?

### ISSUE THREAD

**Issue by d-c-d** [ataradov/usb-sniffer-lite#2]
the linker script sets the CRC as `0xcccccccc` - was there a tool you used to modify the boot section to be accepted by the boot loader?

```
SECTIONS
{
  .boot : ALIGN(4)
  {
    KEEP(*(.boot.entry))
    *(.boot*)
    . = 256-4;
    LONG(0xcccccccc) /* CRC */
  } > boot
```

**Comment by ataradov** [comment]
This is the tool https://github.com/ataradov/tools/tree/master/bin2uf2
I'll add it to the description.

**Comment by ataradov** [comment]
Added a link to the CRC tool.
