### ISSUE TITLE
Windows 7 driver issues

### ISSUE THREAD

**Issue by kovapatrik** [ataradov/usb-sniffer-lite#22]
So I'm trying to use this inside a Windows 7 VM, and the driver doesn't install itself on this OS. I tried to use the FTDI VCP drivers but without success. What driver should I use for this to work?

**Comment by ataradov** [comment]
You need an INF file referencing usbser.sys driver. There is not a universal one. Here is one from a long time ago for a Atmel Raven USB Stick. You will need to edit this and change VID/PID and optionally strings.
[RZUsbStick.txt](https://github.com/user-attachments/files/17549869/RZUsbStick.txt) (rename to *.inf)

But really, I have no idea. Win7 is 5 years out of support.

**Comment by kovapatrik** [comment]
I just found a similar solution just after I made the issue, but thanks for the help!!
