### ISSUE TITLE
Nice, it would be interesting to add other protocols - Alternative for the Saleae Logic Analyzer

### ISSUE THREAD

**Issue by rtek1000** [ataradov/usb-sniffer-lite#5]
Hi,

Very cool this project with RP2040, it would be interesting to add other protocols.

As the Saleae analyzer also has an interface application for Windows, Linux and MAC, maybe it could be interesting to choose to add protocols not supported by Saleae to the RP2040.

Here is a list of protocols that Saleae's logic analyzer supports:

> The Saleae Logic software includes the following protocol analyzers:
> 
> - 1-Wire
> - Asynchronous Serial
> - Atmel SWI (Single Wire Interface)
> - BISS-C
> - CAN (Controller Area Network)
> - DMX512
> - HD44780 Parallel LCD
> - HDLC (High-Level Data Link Control)
> - HDMI-CEC
> - I2C
> - I2S Audio / PCM
> - I3C (see section below)
> - JTAG
> - LIN (Local Interconnect Network)
> - MDIO (Management Data Input/Output)
> - MIDI
> - Manchester (Differential, Bi-Phase Space, and Bi-Phase Mark)
> - Modbus RTU & ASCII
> - PS2 Keyboard & Mouse
> - SMBus (includes PMBus and Smart Battery)
> - SPI (Serial Peripheral Interface)
> - SWD (ARM Serial Wire Debug)
> - Synchronous Parallel
> - USB Low Speed and Full Speed
> - I3C Protocol Support

https://support.saleae.com/protocol-analyzers/supported-protocols

![protocol-decoders](https://github.com/ataradov/usb-sniffer-lite/assets/8660811/95a7d9bb-c8d2-4f3a-b8c5-a01116e4a1c7)

**Comment by ataradov** [comment]
Why would I do that? This is a very specifically USB sniffer. If you need other protocols, use other tools. There is no point in combining all in one, it will never be as good as dedicated tools.

Also, this PR2040 will never get even remotely close to the performance required to clone Saleae. You will get a toy, no more.
