### ISSUE TITLE
Here is an udev rule 

### ISSUE THREAD

**Issue by FauthD** [ataradov/usb-sniffer-lite#8]
Hi, 
this set of udev rules does:
- Puts device into group plugdev
- Create symlink /dev/usbsniffer
- Ensure the ModemManager does not touch our device

## Reasons:
If the user is member of group plugdev, there is no need for sudo.
/dev/ttyACMx is volatile and the x can change from boot to boot. The symlink stays constant.
(You could also use the /dev/serial/by-id/xxxxxx, but that is not too easy to remember.
The Modem Manager tries to talk to ttyACMx devices for about 20 seconds after plugin. That can disturb communication.

[70-UsbSniffer.rules.txt](https://github.com/ataradov/usb-sniffer-lite/files/14072886/70-UsbSniffer.rules.txt)

Remove the .txt from the name and copy to /etc&udev/rules.d.

Feel free to add it to the repo.

## Contents:
```###############################################################################################
# CDC-ACM interface for USB Sniffer
# Create symlinks for CDC-ACM
# Put device into group plugdev
# Ensure the ModemManager does not touch our device

ATTRS{idVendor}=="6666", SUBSYSTEM=="tty", SYMLINK+="usbsniffer", MODE="660", GROUP="plugdev"

ATTRS{idVendor}=="6666", SUBSYSTEM=="tty", \
	ENV{ID_MM_PORT_IGNORE}="1", ENV{ID_MM_DEVICE_IGNORE}="1", ENV{ID_MM_CANDIDATE}="0"
```

**Comment by ataradov** [comment]
Added it (https://github.com/ataradov/usb-sniffer-lite/blob/main/bin/90-usb-sniffer-lite.rules) with additional product match, since I have a lot of stuff with VID==6666.
